# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ROOT: ${{ github.workspace }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish for Windows
      run: dotnet publish -c Release -r win-x64 --self-contained false --no-restore --no-build -o ${{ env.ROOT }}/publish/win-x64

    - name: Publish for Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained false --no-restore --no-build -o ${{ env.ROOT }}/publish/linux-x64
    
    - name: Publish for MacOS
      run: dotnet publish -c Release -r osx-x64 --self-contained false --no-restore --no-build -o ${{ env.ROOT }}/publish/osx-x64

    - name: Zip Windows Asset
      run: |
        cd ${{ env.ROOT }}/publish/win-x64
        zip -r ${{ env.ROOT }}/publish/win-x64.zip .
    
    - name: Zip Linux Asset
      run: |
        cd ${{ env.ROOT }}/publish/linux-x64
        zip -r ${{ env.ROOT }}/publish/linux-x64.zip .
    
    - name: Zip MacOS Asset
      run: |
        cd ${{ env.ROOT }}/publish/osx-x64
        zip -r ${{ env.ROOT }}/publish/osx-x64.zip .
        
    