# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ROOT: ${{ github.workspace }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Create output directory
      run: mkdir -p ./publish/macos

    - name: Build for MacOS
      run: dotnet publish --configuration Release --runtime osx-x64 --self-contained true && cp ./Program/bin/Release/net7.0/osx-x64/publish/Program ./publish/macos

    - name: Create run script for macOS
      run: touch ./publish/macos/help.shh && echo '#!/bin/zsh' > ./publish/macos/help.sh && echo 'exec ./Program "$@"' >> ./publish/macos/help.sh

    - name: Create add command script for macOS
      run: touch ./publish/macos/add-command.sh && echo '#!/bin/zsh' > ./publish/macos/add-command.sh && echo 'echo "alias help="$(pwd)/help.sh"" >> ~/.zshrc' >> ./publish/macos/add-command.sh

    - name: Zip files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r osx-command-line-help.zip ./publish/macos/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./osx-command-line-help.zip
